"""Agentic Firewall (AFW) - Core security layer for any app."""

import logging
import re
import json
from pathlib import Path
from typing import List, Dict, Tuple, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

DEFAULT_POLICY = {
    "allowed_paths": [
        # Standard project directories
        "src/.*",
        "app/.*",
        "apps/.*",
        "backend/.*",
        "frontend/.*",
        "server/.*",
        "client/.*",
        "api/.*",
        "web/.*",
        "packages/.*",
        "services/.*",
        "lib/.*",
        "libs/.*",
        "utils/.*",
        "helpers/.*",
        "components/.*",
        "pages/.*",
        "routes/.*",
        "models/.*",
        "views/.*",
        "controllers/.*",
        "middleware/.*",
        "db/.*",
        "database/.*",
        "migrations/.*",
        "tests/.*",
        "test/.*",
        "spec/.*",
        "docs/.*",
        "public/.*",
        "static/.*",
        "assets/.*",
        "templates/.*",
        "scripts/.*",
        "config/.*",
        "infra/.*",
        "ops/.*",
        "docker/.*",
        "deploy/.*",
        "\\.github/.*",
        # Root-level files commonly generated by LLMs
        "README.md",
        "LICENSE.*",
        "pyproject.toml",
        "setup\\.py",
        "setup\\.cfg",
        "requirements.*\\.txt",
        "package\\.json",
        "package-lock\\.json",
        "pnpm-lock\\.yaml",
        "yarn\\.lock",
        "tsconfig\\.json",
        "vite\\.config\\.[jt]s",
        "tailwind\\.config\\.[jt]s",
        "postcss\\.config\\.[jt]s",
        "next\\.config\\.[jt]s",
        "webpack\\.config\\.[jt]s",
        "\\.eslintrc.*",
        "\\.prettierrc.*",
        "\\.babelrc",
        "babel\\.config\\.[jt]s",
        "jest\\.config\\.[jt]s",
        "vitest\\.config\\.[jt]s",
        "Cargo\\.toml",
        "Cargo\\.lock",
        "go\\.mod",
        "go\\.sum",
        "Gemfile",
        "Gemfile\\.lock",
        "Rakefile",
        "Makefile",
        "Dockerfile",
        "docker-compose\\.ya?ml",
        "\\.dockerignore",
        "\\.gitignore",
        "Procfile",
        "render\\.yaml",
        "railway\\.toml",
        "vercel\\.json",
        "fly\\.toml",
        # Root source files (main entry points)
        "main\\.py",
        "manage\\.py",
        "wsgi\\.py",
        "asgi\\.py",
        "server\\.py",
        "index\\.[jt]sx?",
        "index\\.html",
        "index\\.css",
        "\\.env\\.example",
        "\\.env\\.sample",
    ],
    "blocked_paths": [
        "^\\.env$",
        "^.*\\/\\.env$",
        "\\.env\\.local",
        "\\.env\\.production",
        "\\.env\\.development",
        "\\.ssh/.*",
        "\\.aws/.*",
        "\\.gnupg/.*",
        "\\.kube/.*",
        "\\.git/.*",
        "\\.npmrc",
        "\\.pypirc",
        "config/secrets\\.json",
        "config/credentials\\.json",
        ".*/\\.bash_history",
        "/etc/.*",
        "/var/.*",
        "/private/.*",
        "/System/.*"
    ],
    "blocked_patterns": [
        "eval\\(",
        "exec\\(",
        "os\\.system\\(",
        "subprocess\\.run\\(",
        "__import__",
        "getattr\\(",
        "setattr\\(",
        "importlib\\."
    ],
    "blocked_patterns_exempt_extensions": [
        ".sh", ".bash", ".zsh",
        ".yml", ".yaml",
        "Dockerfile", "Makefile",
        ".mk", ".containerfile"
    ],
    "shell_blocked_patterns": [
        "curl\\s+.*\\|\\s*(?:sh|bash)",
        "wget\\s+.*\\|\\s*(?:sh|bash)",
        "nc\\s+-e",
        "\\brm\\s+-rf\\s+/[^.]",
        "chmod\\s+777",
        "mkfifo.*\\/dev\\/tcp",
        "base64\\s+-d.*\\|\\s*(?:sh|bash)"
    ]
}

class AgenticFirewall:
    """Zero-trust middleware for agent tool calls."""

    def __init__(self, policy_path: Optional[Path] = None, audit_log: Optional[Path] = None):
        self.policy = DEFAULT_POLICY
        if policy_path and policy_path.exists():
            try:
                with open(policy_path, "r") as f:
                    self.policy = json.load(f)
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning("Invalid firewall policy at %s (%s), using defaults", policy_path, exc)
        
        self.audit_log = audit_log or Path("firewall_audit.log")

    def validate_file_write(self, filepath: str, content: str) -> Tuple[bool, str]:
        """Validate if a file write is permitted.

        Security model: block dangerous paths first, then allow everything else.
        Agents generate unpredictable directory names (MicAmplifier/, my-app/, etc.)
        so an allowlist approach breaks on real projects. The blocklist is the real
        security boundary.
        """

        # 1. Block dangerous paths (secrets, system files, dotfiles)
        for pattern in self.policy.get("blocked_paths", []):
            if re.search(pattern, filepath):
                self._log_violation(filepath, "BLOCKED_PATH")
                return False, f"Access to sensitive path '{filepath}' is prohibited by policy."

        # Check for Malicious Patterns in Content
        # Shell scripts and CI configs are exempt from *code-level* patterns
        # (subprocess, eval, etc.) but get their own scan for shell exploits.
        exempt_exts = self.policy.get("blocked_patterns_exempt_extensions", [])
        filename = Path(filepath).name
        is_exempt = any(
            filename == ext or filename.endswith(ext)
            for ext in exempt_exts
        )
        if is_exempt:
            # Scoped scanning: shell/CI files get shell-specific exploit checks
            for pattern in self.policy.get("shell_blocked_patterns", []):
                if re.search(pattern, content):
                    self._log_violation(filepath, f"SHELL_EXPLOIT_PATTERN: {pattern}")
                    return False, f"Dangerous shell pattern detected in '{filepath}'."
        else:
            for pattern in self.policy.get("blocked_patterns", []):
                if re.search(pattern, content):
                    self._log_violation(filepath, f"MALICIOUS_CONTENT_PATTERN: {pattern}")
                    return False, f"Potentially malicious code pattern detected in '{filepath}'."

        self._log_event(filepath, "PERMITTED")
        return True, "Success"

    def validate_materialized_env_write(self, filepath: str, source_path: str, content: str) -> Tuple[bool, str]:
        """Allow controlled .env materialization from a documented example file.

        This is for control-plane copies only. Agents still may not generate real
        `.env` files directly.
        """
        normalized = filepath.strip()
        if not (normalized == ".env" or normalized.endswith("/.env")):
            return False, f"Materialized env target '{filepath}' is not a supported .env path."
        if not source_path.strip().endswith(".env.example"):
            return False, f"Materialized env source '{source_path}' must be a .env.example file."

        # Scan content for code-level exploit patterns even though the path is allowed.
        for pattern in self.policy.get("blocked_patterns", []):
            if re.search(pattern, content):
                self._log_violation(filepath, f"MALICIOUS_CONTENT_PATTERN: {pattern}")
                return False, f"Potentially malicious code pattern detected in '{filepath}'."

        self._log_event(filepath, "CONTROLLED_ENV_MATERIALIZATION", source_path)
        return True, "Success"

    def _log_event(self, target: str, action: str, detail: str = ""):
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "target": target,
            "action": action,
            "detail": detail
        }
        with open(self.audit_log, "a") as f:
            f.write(json.dumps(log_entry) + "\n")

    def _log_violation(self, target: str, violation_type: str):
        logger.warning("SECURITY VIOLATION: %s on %s", violation_type, target)
        self._log_event(target, "DENIED", violation_type)
