"""Deterministic bootstrap scaffolds for supported local template families.

These scaffolds only create the structural skeleton for supported local builds.
They do not hardcode domain-specific business logic. The model still owns the
variable project work after bootstrap.
"""

from __future__ import annotations

import json
import re
from typing import Any


def scaffold_supported_task(task: dict, spec: str, decisions: dict) -> str | None:
    """Return deterministic bootstrap files for supported local setup tasks."""
    specialization = str(task.get("specialization", "")).strip().lower()
    if specialization != "setup":
        return None

    family = _template_family(decisions)
    title = _project_title(spec)
    styling = _stack_value(decisions, "styling")

    if family == "web-app":
        return _web_app_setup_response(title, styling=styling, spec=spec)
    if family == "api-only":
        return _api_only_setup_response(title, spec=spec)
    if family == "static-site":
        return _static_site_setup_response(title, spec=spec)
    return None


def scaffold_supported_spec_api_payload(task: dict, spec: str, decisions: dict) -> dict[str, Any] | None:
    """Return a strict Spec API payload for supported deterministic CRUD tasks."""
    family = _template_family(decisions)
    if family not in {"web-app", "api-only"}:
        return None

    specialization = str(task.get("specialization", "")).strip().lower()
    if specialization == "setup":
        deterministic = scaffold_supported_task(task, spec, decisions)
        if deterministic is None:
            return None
        files = _extract_file_blocks(deterministic)
        return _strict_payload(files, notes=["Generated by deterministic Forge setup scaffold."])

    spec_doc = _parse_spec_document(spec)
    if not spec_doc:
        return None

    if specialization == "backend":
        resource = _resource_for_task(task, spec_doc)
        if resource is None:
            return None
        model = _model_for_resource(resource, spec_doc)
        if model is None:
            return None
        files = _crud_backend_files(resource, model, spec)
        contracts = _crud_backend_contracts(resource, model)
        return _strict_payload(
            files,
            contracts=contracts,
            notes=["Generated by deterministic Forge CRUD backend scaffold."],
        )

    if specialization == "frontend" and family == "web-app":
        ui = _ui_for_task(task, spec_doc)
        if ui is None:
            return None
        resource = _resource_for_ui(ui, spec_doc)
        if resource is None:
            return None
        model = _model_for_resource(resource, spec_doc)
        if model is None:
            return None
        files = _crud_frontend_files(resource, model, spec)
        return _strict_payload(
            files,
            notes=["Generated by deterministic Forge CRUD frontend scaffold."],
        )

    if specialization == "test":
        test_case = _test_for_task(task, spec_doc)
        if test_case is None:
            return None
        resource = _resource_for_test(test_case, spec_doc)
        if resource is None:
            return None
        model = _model_for_resource(resource, spec_doc)
        if model is None:
            return None
        files = _crud_test_files(resource, model)
        return _strict_payload(
            files,
            notes=["Generated by deterministic Forge CRUD test scaffold."],
        )

    return None


def _template_family(decisions: dict) -> str:
    if not isinstance(decisions, dict):
        return ""
    family = str(decisions.get("template_family", "")).strip().lower()
    if family:
        return family

    stack = decisions.get("stack", {})
    framework = str(stack.get("framework", "")).strip().lower()
    frontend = str(stack.get("frontend", "")).strip().lower()

    if framework == "fastapi" and frontend == "react":
        return "web-app"
    if framework == "fastapi" and frontend in {"none", ""}:
        return "api-only"
    if framework == "static-html":
        return "static-site"
    return ""


def _stack_value(decisions: dict, key: str) -> str:
    if not isinstance(decisions, dict):
        return ""
    stack = decisions.get("stack", {})
    return str(stack.get(key, "")).strip().lower()


def _project_title(spec: str) -> str:
    match = re.search(r"^#\s*Project:\s*(.+)$", spec, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return "Forge Project"


def _web_app_setup_response(title: str, styling: str, spec: str = "") -> str:
    package_json = {
        "name": _slugify(title),
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview",
        },
        "dependencies": {
            "react": "^18.3.1",
            "react-dom": "^18.3.1",
            "react-router-dom": "^6.28.0",
        },
        "devDependencies": {
            "@vitejs/plugin-react": "^4.3.4",
            "autoprefixer": "^10.4.20",
            "postcss": "^8.4.49",
            "tailwindcss": "^3.4.16",
            "vite": "^5.4.10",
        },
    }

    readme = _web_app_readme(title, spec)

    gitignore = """# Python
__pycache__/
*.py[cod]
.venv/
venv/

# Node
node_modules/
dist/

# Local config
.env
.env.local

# OS / editor
.DS_Store
.vscode/
"""

    backend_stub = f"""from fastapi import FastAPI

app = FastAPI(title="{_escape_py(title)}")


@app.get("/health")
def health():
    return {{"status": "ok"}}
"""

    env_example = """VITE_API_URL=
DATABASE_PATH=backend/site.db
"""

    vite_config = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    host: '127.0.0.1',
    port: 5173,
  },
})
"""

    index_html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

    main_jsx = """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"""

    app_jsx = f"""export default function App() {{
  return (
    <main style={{{{ fontFamily: 'system-ui, sans-serif', padding: '2rem', lineHeight: 1.5 }}}}>
      <h1>{_escape_js(title)}</h1>
      <p>Forge created the project skeleton. Builder tasks will fill in the product-specific UI.</p>
    </main>
  )
}}
"""

    index_css = (
        """@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  min-width: 320px;
}
"""
        if styling == "tailwind"
        else "body { margin: 0; min-width: 320px; }\n"
    )

    files = [
        ("README.md", readme),
        (".gitignore", gitignore),
        ("backend/main.py", backend_stub),
        ("backend/.env.example", "DATABASE_PATH=backend/site.db\n"),
        ("frontend/package.json", json.dumps(package_json, indent=2) + "\n"),
        ("frontend/index.html", index_html),
        ("frontend/vite.config.js", vite_config),
        ("frontend/.env.example", env_example),
        ("frontend/src/main.jsx", main_jsx),
        ("frontend/src/App.jsx", app_jsx),
        ("frontend/src/index.css", index_css),
    ]
    if styling == "tailwind":
        files.extend([
            ("frontend/tailwind.config.js", """export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: { extend: {} },
  plugins: [],
}
"""),
            ("frontend/postcss.config.js", """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""),
        ])

    return _files_response(files)


def _api_only_setup_response(title: str, spec: str = "") -> str:
    readme = _api_only_readme(title, spec)

    gitignore = """__pycache__/
*.py[cod]
.venv/
venv/
.env
.DS_Store
"""

    backend_stub = f"""from fastapi import FastAPI

app = FastAPI(title="{_escape_py(title)}")


@app.get("/health")
def health():
    return {{"status": "ok"}}
"""

    return _files_response([
        ("README.md", readme),
        (".gitignore", gitignore),
        ("backend/main.py", backend_stub),
        ("backend/.env.example", "DATABASE_PATH=backend/site.db\n"),
    ])


def _static_site_setup_response(title: str, spec: str = "") -> str:
    readme = _static_site_readme(title, spec)

    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <main class="page">
      <h1>{title}</h1>
      <p>Forge created the project skeleton. Builder tasks will fill in the product-specific content.</p>
    </main>
    <script src="./script.js"></script>
  </body>
</html>
"""

    css = """.page {
  font-family: system-ui, sans-serif;
  margin: 0 auto;
  max-width: 900px;
  padding: 2rem;
}
"""

    return _files_response([
        ("README.md", readme),
        (".gitignore", ".DS_Store\n"),
        ("index.html", html),
        ("styles.css", css),
        ("script.js", "console.log('Forge static-site bootstrap ready')\n"),
    ])


def _files_response(files: list[tuple[str, str]]) -> str:
    parts = []
    for path, content in files:
        parts.append(f"```file:{path}\n{content.rstrip()}\n```")
    return "\n\n".join(parts) + "\n"


def _strict_payload(
    files: list[tuple[str, str]],
    contracts: dict[str, list[dict[str, Any]]] | None = None,
    notes: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "status": "success",
        "files": [{"path": path, "content": content} for path, content in files],
        "contracts": contracts or {"api": [], "models": [], "events": []},
        "uses_contracts": [],
        "notes": notes or [],
        "requires": [],
    }


def _extract_file_blocks(response: str) -> list[tuple[str, str]]:
    files: list[tuple[str, str]] = []
    for match in re.finditer(r"```file:([^\n]+)\n(.*?)```", response, re.DOTALL):
        files.append((match.group(1).strip(), match.group(2).rstrip() + "\n"))
    return files


def _parse_spec_document(spec: str):
    try:
        from .specapi import parse_spec_text
    except ImportError:
        return None
    doc = parse_spec_text(spec)
    return doc if doc.valid and doc.primitives else None


def _primitive_by_ref(doc, ref: str):
    return next((item for item in doc.primitives if item.ref == ref), None)


def _resource_for_task(task: dict, doc):
    for ref in task.get("inputs", []):
        item = _primitive_by_ref(doc, str(ref))
        if item and item.type == "api.resource":
            return item
    task_id = str(task.get("id", ""))
    if task_id.startswith("backend."):
        name = task_id.split(".", 1)[1]
        return next((item for item in doc.primitives if item.type == "api.resource" and item.name == name), None)
    return None


def _model_for_resource(resource, doc):
    model_name = str(resource.body.get("model") or "")
    return next((item for item in doc.primitives if item.type == "db.model" and item.name == model_name), None)


def _ui_for_task(task: dict, doc):
    for ref in task.get("inputs", []):
        item = _primitive_by_ref(doc, str(ref))
        if item and item.type in {"ui.table", "ui.form", "ui.page"}:
            return item
    task_id = str(task.get("id", ""))
    name = task_id.rsplit(".", 1)[-1] if "." in task_id else task_id
    return next((item for item in doc.primitives if item.type.startswith("ui.") and item.name == name), None)


def _resource_for_ui(ui, doc):
    endpoint = str(ui.body.get("source") or ui.body.get("submit") or "")
    match = re.search(r"/api/([A-Za-z0-9_-]+)", endpoint)
    if match:
        name = match.group(1)
        found = next((item for item in doc.primitives if item.type == "api.resource" and item.name == name), None)
        if found:
            return found
    return next((item for item in doc.primitives if item.type == "api.resource"), None)


def _test_for_task(task: dict, doc):
    for ref in task.get("inputs", []):
        item = _primitive_by_ref(doc, str(ref))
        if item and item.type == "test.case":
            return item
    return next((item for item in doc.primitives if item.type == "test.case"), None)


def _resource_for_test(test_case, doc):
    covered = str(test_case.body.get("covers") or "")
    if covered:
        found = next((item for item in doc.primitives if item.type == "api.resource" and item.name == covered), None)
        if found:
            return found
    return next((item for item in doc.primitives if item.type == "api.resource"), None)


def _field_map(model) -> dict[str, dict[str, Any]]:
    fields = model.body.get("fields", {})
    return fields if isinstance(fields, dict) else {}


def _py_type(field_type: str) -> str:
    normalized = field_type.lower()
    if normalized in {"integer", "int"}:
        return "int"
    if normalized in {"boolean", "bool"}:
        return "bool"
    if normalized in {"money", "float", "decimal"}:
        return "float"
    return "str"


def _crud_backend_files(resource, model, spec: str) -> list[tuple[str, str]]:
    title = _project_title(spec)
    model_name = model.name
    resource_name = resource.name
    fields = _field_map(model)
    actions = {str(item).lower() for item in resource.body.get("actions", [])}
    auth_mode = "jwt" if str(resource.body.get("auth") or "").lower() == "required" else "none"

    schema_fields = []
    insert_names = []
    insert_values = []
    for name, meta in fields.items():
        ftype = _py_type(str(meta.get("type", "string")))
        required = bool(meta.get("required"))
        default = "" if required else " | None = None"
        schema_fields.append(f"    {name}: {ftype}{default}")
        insert_names.append(name)
        insert_values.append(f"item.{name}")

    schema_block = "\n".join(schema_fields) or "    name: str"
    create_model = f"{model_name}Create"
    update_model = f"{model_name}Update"
    table_columns = ",\n        ".join(
        f"{name} TEXT {'NOT NULL' if meta.get('required') else ''}".rstrip()
        for name, meta in fields.items()
    ) or "name TEXT NOT NULL"
    insert_cols = ", ".join(insert_names) or "name"
    insert_placeholders = ", ".join("?" for _ in insert_names) or "?"
    insert_vals = ", ".join(insert_values) or "item.name"

    main = f'''from datetime import datetime
from pathlib import Path
import sqlite3

from fastapi import Depends, FastAPI, Header, HTTPException, status
from pydantic import BaseModel

app = FastAPI(title="{_escape_py(title)}")
DB_PATH = Path(__file__).with_name("site.db")


class {create_model}(BaseModel):
{schema_block}


class {update_model}(BaseModel):
{_optional_schema_block(fields)}


class {model_name}({create_model}):
    id: int
    created_at: str
    updated_at: str


def require_auth(authorization: str | None = Header(default=None)) -> None:
    if "{auth_mode}" == "none":
        return
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Missing bearer token")


def db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    with db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS {resource_name} (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                {table_columns},
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )


@app.on_event("startup")
def on_startup() -> None:
    init_db()


@app.get("/health")
def health():
    return {{"status": "ok"}}
'''
    if "list" in actions:
        main += f'''

@app.get("/api/{resource_name}", response_model=list[{model_name}])
def list_{resource_name}(_: None = Depends(require_auth)):
    init_db()
    with db() as conn:
        rows = conn.execute("SELECT * FROM {resource_name} ORDER BY id DESC").fetchall()
    return [dict(row) for row in rows]
'''
    if "get" in actions:
        main += f'''

@app.get("/api/{resource_name}/{{item_id}}", response_model={model_name})
def get_{resource_name}(item_id: int, _: None = Depends(require_auth)):
    init_db()
    with db() as conn:
        row = conn.execute("SELECT * FROM {resource_name} WHERE id = ?", (item_id,)).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return dict(row)
'''
    if "create" in actions:
        main += f'''

@app.post("/api/{resource_name}", response_model={model_name}, status_code=201)
def create_{resource_name}(item: {create_model}, _: None = Depends(require_auth)):
    init_db()
    now = datetime.utcnow().isoformat()
    with db() as conn:
        cursor = conn.execute(
            "INSERT INTO {resource_name} ({insert_cols}, created_at, updated_at) VALUES ({insert_placeholders}, ?, ?)",
            ({insert_vals}, now, now),
        )
        row = conn.execute("SELECT * FROM {resource_name} WHERE id = ?", (cursor.lastrowid,)).fetchone()
    return dict(row)
'''
    if "update" in actions:
        assignments = ", ".join(f"{name} = ?" for name in fields) or "name = ?"
        values_expr = ", ".join(f"merged.get('{name}')" for name in fields) or "merged.get('name')"
        main += f'''

@app.patch("/api/{resource_name}/{{item_id}}", response_model={model_name})
def update_{resource_name}(item_id: int, item: {update_model}, _: None = Depends(require_auth)):
    init_db()
    data = item.dict(exclude_unset=True)
    if not data:
        raise HTTPException(status_code=400, detail="No updates provided")
    with db() as conn:
        current = conn.execute("SELECT * FROM {resource_name} WHERE id = ?", (item_id,)).fetchone()
        if current is None:
            raise HTTPException(status_code=404, detail="{model_name} not found")
        merged = dict(current)
        merged.update(data)
        merged["updated_at"] = datetime.utcnow().isoformat()
        conn.execute(
            "UPDATE {resource_name} SET {assignments}, updated_at = ? WHERE id = ?",
            ({values_expr}, merged["updated_at"], item_id),
        )
        row = conn.execute("SELECT * FROM {resource_name} WHERE id = ?", (item_id,)).fetchone()
    return dict(row)
'''
    if "delete" in actions:
        main += f'''

@app.delete("/api/{resource_name}/{{item_id}}", status_code=204)
def delete_{resource_name}(item_id: int, _: None = Depends(require_auth)):
    init_db()
    with db() as conn:
        cursor = conn.execute("DELETE FROM {resource_name} WHERE id = ?", (item_id,))
    if cursor.rowcount == 0:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return None
'''

    return [
        ("backend/main.py", main),
        ("backend/requirements.txt", "fastapi\nuvicorn[standard]\npydantic\n"),
    ]


def _optional_schema_block(fields: dict[str, dict[str, Any]]) -> str:
    if not fields:
        return "    name: str | None = None"
    return "\n".join(
        f"    {name}: {_py_type(str(meta.get('type', 'string')))} | None = None"
        for name, meta in fields.items()
    )


def _crud_backend_contracts(resource, model) -> dict[str, list[dict[str, Any]]]:
    resource_name = resource.name
    model_name = model.name
    fields = {name: str(meta.get("type", "string")) for name, meta in _field_map(model).items()}
    actions = {str(item).lower() for item in resource.body.get("actions", [])}
    auth = "jwt" if str(resource.body.get("auth") or "").lower() == "required" else "none"
    api = []
    if "list" in actions:
        api.append({"method": "GET", "path": f"/api/{resource_name}", "response_schema": {"type": "array", "items": model_name}, "auth": auth})
    if "get" in actions:
        api.append({"method": "GET", "path": f"/api/{resource_name}/{{id}}", "response_schema": {"type": model_name}, "auth": auth})
    if "create" in actions:
        api.append({"method": "POST", "path": f"/api/{resource_name}", "request_schema": fields, "response_schema": {"type": model_name}, "auth": auth})
    if "update" in actions:
        api.append({"method": "PATCH", "path": f"/api/{resource_name}/{{id}}", "request_schema": fields, "response_schema": {"type": model_name}, "auth": auth})
    if "delete" in actions:
        api.append({"method": "DELETE", "path": f"/api/{resource_name}/{{id}}", "response_schema": {"status": "deleted"}, "auth": auth})
    return {
        "api": api,
        "models": [{"name": model_name, "fields": fields}],
        "events": [],
    }


def _crud_frontend_files(resource, model, spec: str) -> list[tuple[str, str]]:
    title = _project_title(spec)
    resource_name = resource.name
    model_name = model.name
    fields = _field_map(model)
    field_names = list(fields) or ["name"]
    default_status = "lead" if "status" in fields else ""

    initial_state = ", ".join(
        f"{name}: '{default_status if name == 'status' else ''}'"
        for name in field_names
    )
    form_inputs = "\n".join(_form_input(name, meta) for name, meta in fields.items()) or _form_input("name", {"type": "string", "required": True})
    table_headers = "\n".join(f"              <th>{name.title()}</th>" for name in field_names)
    table_cells = "\n".join(f"              <td>{{item.{name}}}</td>" for name in field_names)

    api_js = f"""const API_URL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000'
const TOKEN = import.meta.env.VITE_AUTH_TOKEN || 'dev-token'

async function request(path, options = {{}}) {{
  const response = await fetch(`${{API_URL}}${{path}}`, {{
    ...options,
    headers: {{
      'Content-Type': 'application/json',
      Authorization: `Bearer ${{TOKEN}}`,
      ...(options.headers || {{}}),
    }},
  }})
  if (!response.ok) {{
    const detail = await response.text()
    throw new Error(detail || `Request failed: ${{response.status}}`)
  }}
  if (response.status === 204) return null
  return response.json()
}}

export function list{model_name}() {{
  return request('/api/{resource_name}')
}}

export function create{model_name}(payload) {{
  return request('/api/{resource_name}', {{
    method: 'POST',
    body: JSON.stringify(payload),
  }})
}}

export function update{model_name}(id, payload) {{
  return request(`/api/{resource_name}/${{id}}`, {{
    method: 'PATCH',
    body: JSON.stringify(payload),
  }})
}}

export function delete{model_name}(id) {{
  return request(`/api/{resource_name}/${{id}}`, {{ method: 'DELETE' }})
}}
"""

    app_jsx = f"""import {{ useEffect, useMemo, useState }} from 'react'
import {{ create{model_name}, delete{model_name}, list{model_name}, update{model_name} }} from './api/{resource_name}'
import './index.css'

const emptyForm = {{ {initial_state} }}

export default function App() {{
  const [items, setItems] = useState([])
  const [form, setForm] = useState(emptyForm)
  const [editingId, setEditingId] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const title = useMemo(() => editingId ? 'Update {model_name}' : 'Add {model_name}', [editingId])

  async function refresh() {{
    setLoading(true)
    setError('')
    try {{
      setItems(await list{model_name}())
    }} catch (err) {{
      setError(err.message)
    }} finally {{
      setLoading(false)
    }}
  }}

  useEffect(() => {{
    refresh()
  }}, [])

  function updateField(event) {{
    const {{ name, value }} = event.target
    setForm((current) => ({{ ...current, [name]: value }}))
  }}

  async function submit(event) {{
    event.preventDefault()
    setError('')
    try {{
      if (editingId) {{
        await update{model_name}(editingId, form)
      }} else {{
        await create{model_name}(form)
      }}
      setForm(emptyForm)
      setEditingId(null)
      await refresh()
    }} catch (err) {{
      setError(err.message)
    }}
  }}

  function edit(item) {{
    setEditingId(item.id)
    setForm({{ {", ".join(f"{name}: item.{name} || ''" for name in field_names)} }})
  }}

  async function remove(id) {{
    setError('')
    try {{
      await delete{model_name}(id)
      await refresh()
    }} catch (err) {{
      setError(err.message)
    }}
  }}

  return (
    <main className="app-shell">
      <section className="toolbar">
        <div>
          <p className="eyebrow">Freelancer CRM</p>
          <h1>{_escape_js(title)}</h1>
        </div>
        <button onClick={{refresh}} disabled={{loading}}>Refresh</button>
      </section>

      {{error && <div className="alert">{{error}}</div>}}

      <section className="workspace">
        <form className="panel form-panel" onSubmit={{submit}}>
          <h2>{{title}}</h2>
{form_inputs}
          <button type="submit">{{editingId ? 'Save changes' : 'Create {model_name}'}}</button>
        </form>

        <section className="panel table-panel">
          <h2>{model_name} Pipeline</h2>
          {{loading ? (
            <p>Loading...</p>
          ) : (
            <table>
              <thead>
                <tr>
{table_headers}
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {{items.map((item) => (
                  <tr key={{item.id}}>
{table_cells}
                    <td className="actions">
                      <button type="button" onClick={{() => edit(item)}}>Edit</button>
                      <button type="button" onClick={{() => remove(item.id)}}>Delete</button>
                    </td>
                  </tr>
                ))}}
              </tbody>
            </table>
          )}}
        </section>
      </section>
    </main>
  )
}}
"""

    css = """body {
  margin: 0;
  min-width: 320px;
  background: #f7f7f4;
  color: #202124;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

button, input, select {
  font: inherit;
}

button {
  border: 1px solid #202124;
  background: #202124;
  color: white;
  padding: 0.55rem 0.8rem;
  cursor: pointer;
}

button:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.app-shell {
  max-width: 1120px;
  margin: 0 auto;
  padding: 2rem;
}

.toolbar {
  align-items: center;
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.eyebrow {
  color: #62605c;
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0;
  margin: 0 0 0.35rem;
  text-transform: uppercase;
}

h1, h2 {
  margin: 0;
}

.workspace {
  display: grid;
  gap: 1rem;
  grid-template-columns: 320px minmax(0, 1fr);
}

.panel {
  background: white;
  border: 1px solid #d9d8d2;
  border-radius: 6px;
  padding: 1rem;
}

.form-panel {
  display: grid;
  gap: 0.8rem;
  align-content: start;
}

label {
  display: grid;
  gap: 0.35rem;
  color: #4d4b47;
  font-size: 0.9rem;
}

input, select {
  border: 1px solid #c8c6bf;
  border-radius: 4px;
  padding: 0.55rem 0.65rem;
}

.alert {
  background: #fff1f0;
  border: 1px solid #e0aaa2;
  border-radius: 6px;
  margin-bottom: 1rem;
  padding: 0.75rem;
}

table {
  border-collapse: collapse;
  margin-top: 1rem;
  width: 100%;
}

th, td {
  border-bottom: 1px solid #e6e4dd;
  padding: 0.7rem;
  text-align: left;
}

.actions {
  display: flex;
  gap: 0.5rem;
}

@media (max-width: 780px) {
  .workspace {
    grid-template-columns: 1fr;
  }
}
"""

    return [
        (f"frontend/src/api/{resource_name}.js", api_js),
        ("frontend/src/App.jsx", app_jsx),
        ("frontend/src/index.css", css),
        ("frontend/.env.example", "VITE_API_URL=http://127.0.0.1:8000\nVITE_AUTH_TOKEN=dev-token\n"),
    ]


def _form_input(name: str, meta: dict[str, Any]) -> str:
    field_type = str(meta.get("type", "string"))
    if field_type.startswith("enum[") and field_type.endswith("]"):
        options = [item.strip() for item in field_type[5:-1].split(",") if item.strip()]
        option_tags = "\n".join(f"              <option value=\"{item}\">{item}</option>" for item in options)
        return f"""          <label>
            {name.title()}
            <select name="{name}" value={{form.{name}}} onChange={{updateField}}>
{option_tags}
            </select>
          </label>"""
    input_type = "email" if field_type == "email" else "text"
    required = " required" if meta.get("required") else ""
    return f"""          <label>
            {name.title()}
            <input name="{name}" type="{input_type}" value={{form.{name}}} onChange={{updateField}}{required} />
          </label>"""


def _crud_test_files(resource, model) -> list[tuple[str, str]]:
    resource_name = resource.name
    fields = _field_map(model)
    create_payload = _example_payload(fields)
    update_payload = _example_update_payload(fields)
    first_field = next(iter(fields), "name")
    create_json = json.dumps(create_payload, sort_keys=True)
    update_json = json.dumps(update_payload, sort_keys=True)
    test_py = f"""from fastapi.testclient import TestClient

from backend.main import app


client = TestClient(app)
headers = {{"Authorization": "Bearer test-token"}}


def test_{resource_name}_crud_flow():
    created = client.post(
        "/api/{resource_name}",
        json={create_json},
        headers=headers,
    )
    assert created.status_code == 201
    item = created.json()
    assert item["{first_field}"] == {json.dumps(create_payload.get(first_field))}

    listed = client.get("/api/{resource_name}", headers=headers)
    assert listed.status_code == 200
    assert any(row["id"] == item["id"] for row in listed.json())

    updated = client.patch(
        f"/api/{resource_name}/{{item['id']}}",
        json={update_json},
        headers=headers,
    )
    assert updated.status_code == 200
    assert updated.json()["{next(iter(update_payload), first_field)}"] == {json.dumps(next(iter(update_payload.values()), create_payload.get(first_field)))}

    deleted = client.delete(f"/api/{resource_name}/{{item['id']}}", headers=headers)
    assert deleted.status_code == 204
"""
    return [(f"tests/test_{resource_name}.py", test_py)]


def _example_payload(fields: dict[str, dict[str, Any]]) -> dict[str, Any]:
    if not fields:
        return {"name": "Acme Studio"}
    payload: dict[str, Any] = {}
    for name, meta in fields.items():
        field_type = str(meta.get("type", "string"))
        payload[name] = _example_value(name, field_type, updated=False)
    return payload


def _example_update_payload(fields: dict[str, dict[str, Any]]) -> dict[str, Any]:
    if not fields:
        return {"name": "Acme Studio Updated"}
    name, meta = next(iter(fields.items()))
    if "status" in fields:
        name, meta = "status", fields["status"]
    return {name: _example_value(name, str(meta.get("type", "string")), updated=True)}


def _example_value(name: str, field_type: str, updated: bool) -> Any:
    if field_type.startswith("enum[") and field_type.endswith("]"):
        options = [item.strip() for item in field_type[5:-1].split(",") if item.strip()]
        if not options:
            return "updated" if updated else "value"
        return options[min(1, len(options) - 1)] if updated else options[0]
    normalized = field_type.lower()
    if normalized == "email":
        return "updated@example.test" if updated else "ops@example.test"
    if normalized in {"integer", "int"}:
        return 2 if updated else 1
    if normalized in {"boolean", "bool"}:
        return bool(updated)
    if normalized in {"money", "float", "decimal"}:
        return 20.0 if updated else 10.0
    return f"{name.title()} Updated" if updated else "Acme Studio"


def _web_app_readme(title: str, spec: str) -> str:
    what = _section_text(spec, "What") or "A small full-stack web application generated by Forge."
    users = _bullet_list(spec, "Users")
    features = _bullet_list(spec, "Features")
    pages = _bullet_list(spec, "Pages")
    endpoints = _bullet_list(spec, "API Endpoints")
    stack = _section_text(spec, "Stack") or "React + Vite, FastAPI, SQLite"

    sections = [
        f"# {title}",
        "",
        "## Overview",
        what,
        "",
        "## Stack",
        f"- {stack}",
    ]

    if users:
        sections.extend(["", "## Users", *[f"- {item}" for item in users]])
    if features:
        sections.extend(["", "## Initial Scope", *[f"- {item}" for item in features]])
    if pages:
        sections.extend(["", "## Pages", *[f"- {item}" for item in pages]])
    if endpoints:
        sections.extend(["", "## API Endpoints", *[f"- {item}" for item in endpoints]])

    sections.extend([
        "",
        "## Project Structure",
        "- `backend/main.py` starts the FastAPI application.",
        "- `backend/routes/` is where API route modules should live.",
        "- `frontend/src/App.jsx` is the frontend shell.",
        "- `frontend/src/pages/` is where page-level views should live.",
        "- `frontend/src/components/` is where shared UI components should live.",
        "- `frontend/src/api/` is where frontend API clients should live.",
        "",
        "## Development",
        "Backend:",
        "```bash",
        "python backend/main.py",
        "```",
        "",
        "Frontend:",
        "```bash",
        "cd frontend",
        "npm install",
        "npm run dev",
        "```",
        "",
        "Combined via Forge:",
        "```bash",
        "forge dev",
        "```",
        "",
        "## Environment",
        "- `backend/.env.example` documents backend-local settings.",
        "- `frontend/.env.example` documents frontend-local settings.",
        "- Forge can materialize local `.env` files from `.env.example` when policy allows it.",
        "- Fill in any real values locally and do not commit secrets.",
    ])
    return "\n".join(sections) + "\n"


def _api_only_readme(title: str, spec: str) -> str:
    what = _section_text(spec, "What") or "A small API service generated by Forge."
    features = _bullet_list(spec, "Features")
    endpoints = _bullet_list(spec, "API Endpoints")

    sections = [
        f"# {title}",
        "",
        "## Overview",
        what,
        "",
        "## Stack",
        "- FastAPI",
        "- SQLite",
    ]
    if features:
        sections.extend(["", "## Initial Scope", *[f"- {item}" for item in features]])
    if endpoints:
        sections.extend(["", "## API Endpoints", *[f"- {item}" for item in endpoints]])
    sections.extend([
        "",
        "## Project Structure",
        "- `backend/main.py` starts the FastAPI application.",
        "- `backend/routes/` is where route modules should live.",
        "",
        "## Development",
        "```bash",
        "python backend/main.py",
        "```",
        "",
        "## Environment",
        "- `backend/.env.example` documents backend-local settings.",
        "- Forge can materialize a local `.env` from `.env.example` when policy allows it.",
    ])
    return "\n".join(sections) + "\n"


def _static_site_readme(title: str, spec: str) -> str:
    what = _section_text(spec, "What") or "A static site generated by Forge."
    features = _bullet_list(spec, "Features")
    pages = _bullet_list(spec, "Pages")

    sections = [
        f"# {title}",
        "",
        "## Overview",
        what,
        "",
        "## Stack",
        "- Plain HTML",
        "- Plain CSS",
        "- Plain JavaScript",
    ]
    if features:
        sections.extend(["", "## Initial Scope", *[f"- {item}" for item in features]])
    if pages:
        sections.extend(["", "## Pages", *[f"- {item}" for item in pages]])
    sections.extend([
        "",
        "## Project Structure",
        "- `index.html` is the main document.",
        "- `styles.css` contains presentation styles.",
        "- `script.js` contains browser-side behavior.",
        "",
        "## Development",
        "Open `index.html` in a browser or serve the directory with a static server.",
    ])
    return "\n".join(sections) + "\n"


def _section_text(spec: str, header: str) -> str:
    pattern = rf"^##\s+{re.escape(header)}\s*$"
    match = re.search(pattern, spec, re.MULTILINE)
    if not match:
        return ""
    start = match.end()
    remainder = spec[start:]
    next_header = re.search(r"^##\s+", remainder, re.MULTILINE)
    block = remainder[: next_header.start()] if next_header else remainder
    return " ".join(line.strip() for line in block.strip().splitlines() if line.strip())


def _bullet_list(spec: str, header: str) -> list[str]:
    pattern = rf"^##\s+{re.escape(header)}\s*$"
    match = re.search(pattern, spec, re.MULTILINE)
    if not match:
        return []
    start = match.end()
    remainder = spec[start:]
    next_header = re.search(r"^##\s+", remainder, re.MULTILINE)
    block = remainder[: next_header.start()] if next_header else remainder
    items: list[str] = []
    for line in block.strip().splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            items.append(stripped[2:].strip())
    return items


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "forge-project"


def _escape_js(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _escape_py(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
